type Producto {
  id: ID!
  nombre: String
  precio: Float
  imagen: String
}

type Query {
  verProductos(id: ID): [Producto]
}


type Mutation {
  agregarProducto(nombre: String, precio: Float, imagen: String): Producto
  modificarProducto( id:ID,
  nombre: String,
  precio: Float,
  imagen: String): Producto
  eliminarProducto(id:ID): Producto
}
